@startuml
title UC - GET Request of Functionality Objects

skinparam sequenceMessageAlign center
skinparam actorBackgroundColor white
skinparam participantBackgroundColor white
skinparam sequenceReferenceBackgroundColor white
skinparam sequenceReferenceHeaderBackgroundColor white
skinparam sequenceGroupBackgroundColor white


autonumber
!pragma teoz true
box " <<System>>\n:SmartHome" #DarkGrey
box "<<Subsystem>>\n :Frontend" #LightGrey
participant "<<Container>>\n  :UI" as frontend
end box
box "<<Subsystem>>\n :Backend" #LightGrey
  participant ":Server" as server <<Container>>
end box
end box


[o-> frontend: Request to get Objects
activate frontend
frontend -> server: GET Objects Request
activate server
server-->frontend: Objects requested JSON
deactivate server
[o<--frontend: Objects requested
deactivate frontend

legend bottom
 **This request can be included in:**
|= Request GET |= Response |
|= /sensorfunctionality (UC07.1) |= List<SensorFunctionalityDTO> |
|= /actuatorfunctionality (UC12.1) |= List<ActuatorFunctionalityDTO> |
end legend


@enduml