services:

  database:
    container_name: database
    build:
      context: .
      dockerfile: DockerfileDatabase
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=5
      - MARIADB_DATABASE=smarthome
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - "database"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: DockerfileFrontend
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge