@startuml
'https://plantuml.com/sequence-diagram
title US09 - As a Power User [or Administrator], I want to get a list of all devices in a house, grouped by device functionality types. It must include device location. Main success case

autonumber

!pragma teoz true

box " <<SubSystem>>\n  <<Container>>\n    :Backend " #DarkGrey
box " <<Component>>\n    :Server" #LightGrey
participant ":ListAllDevicesInHouseByFunctionalityController" as US09Ctrl

'Participants for DTO conversion'
participant ":ActuatorFunctionalityMapperDTO" as ActuatorFunctionalityMapper
participant ":SensorFunctionalityMapperDTO" as SensorFunctionalityMapper
participant ":RoomMapperDTO" as RoomMapper
participant ":DeviceMapperDTO" as DeviceMapper
participant "mapDTOGrouped:\nMap<Object, Map<RoomDTO, DeviceDTO>>" as mapDTOGrouped

participant "actuatorFunctionalityDTO:\nActuatorFunctionalityDTO" as ActuatorFunctionalityDTO
participant "sensorFunctionalityDTO:\nSensorFunctionalityDTO" as SensorFunctionalityDTO

participant "roomDTOAndDeviceDTOMap:\nMap<RoomID, DeviceID>" as roomDTOAndDeviceDTOMap
participant "roomDTO:\nRoomDTO" as RoomDTO
participant "deviceDTO:\nDeviceDTO" as DeviceDTO
end box
end box

activate US09Ctrl
US09Ctrl --> ActuatorFunctionalityMapper**: <<creates>>
US09Ctrl --> SensorFunctionalityMapper**: <<creates>>
US09Ctrl --> RoomMapper**: <<creates>>
US09Ctrl --> DeviceMapper**: <<creates>>

US09Ctrl --> mapDTOGrouped**: <<creates>>

loop for each entry in mainMap
    alt if Object is an instance of ActuatorFunctionalityID
        US09Ctrl -> ActuatorFunctionalityMapper: actuatorFunctionalityToDTO(actuatorFunctionalityID)
        activate ActuatorFunctionalityMapper
        ActuatorFunctionalityMapper --> ActuatorFunctionalityDTO**: <<creates>>
    else if Object is an instance of SensorFunctionalityID
        US09Ctrl -> SensorFunctionalityMapper: sensorFunctionalityToDTO(sensorFunctionalityID)
        activate SensorFunctionalityMapper
        SensorFunctionalityMapper --> SensorFunctionalityDTO**: <<creates>>

    US09Ctrl --> roomDTOAndDeviceDTOMap**: <<creates>>
        loop for each entry in Map<RoomID, DeviceID>
            US09Ctrl -> RoomMapper: roomToDTO(roomID)
            activate RoomMapper
            RoomMapper --> RoomDTO**: <<creates>>

            US09Ctrl -> DeviceMapper: deviceToDTO(deviceID)
            activate DeviceMapper
            DeviceMapper --> DeviceDTO**: <<creates>>
            US09Ctrl -> roomDTOAndDeviceDTOMap: put(roomDTO, deviceDTO)
        end
    US09Ctrl -> mapDTOGrouped: put(Object, roomDTOAndDeviceDTOMap)
    end
end

deactivate US09Ctrl
[o<-- US09Ctrl: mapDTOGrouped
'END SECTION
@enduml