@startuml
autonumber
!pragma teoz true

box "<<SubSystem>>\n:Backend" #DarkGrey
box " <<Container>>\n:Server" #LightGrey

participant ":ValueService" as service <<Component>>
participant ":InstantTimeValueRepository" as instantRepo <<Component>>
participant ":PeriodTimeValueRepository" as periodRepo <<Component>>
participant ":InstantTimeLocationValueRepository" as instantLocationRepo <<Component>>
end box

ref over service:UC33-ListAllMeasurementsOfDeviceInPeriod]
opt if serviceMethodToCall equals listInstantValuesForSensorID

    activate service
    service -> service: listInstantValuesForSensorID(sensorID, startInterval, endInterval)
    service -> instantRepo: findBySensorIdBetweenPeriodOfTime(sensorID, startInterval, endInterval)
    activate instantRepo
    instantRepo --> service: List<Value> listOfValues
    deactivate instantRepo

else if serviceMethodToCall equals listPeriodValuesForSensorID

    service -> service: listPeriodValuesForSensorID(sensorID, startInterval, endInterval)
    service -> periodRepo: findBySensorIdBetweenPeriodOfTime(sensorID, startInterval, endInterval)
    activate periodRepo
    periodRepo --> service: List<Value> listOfValues
    deactivate periodRepo

else if serviceMethodToCall equals listInstantLocationValuesForSensorID

    service -> service: listInstantLocationValuesForSensorID(sensorID, startInterval, endInterval)
    service -> instantLocationRepo: findBySensorIdBetweenPeriodOfTime(sensorID, startInterval, endInterval)
    activate instantLocationRepo
    instantLocationRepo --> service: List<Value> listOfValues
    deactivate instantLocationRepo

end
ref over service:UC33-ListAllMeasurementsOfDeviceInPeriod]
@enduml