@startuml
'https://plantuml.com/sequence-diagram
autonumber
title UC3.2 - Edit Room

autonumber
!pragma teoz true
box " <<System>>\n:SmartHome" #DarkGrey
box "<<Subsystem>>\n :Backend" #LightGrey
  participant ":Server" as server <<Container>>
end box

[o->server: Edit Room
activate server
server->server: Find Room
server->server: Edit Room and Save
[o<--server: Edited room
deactivate server
@enduml