@startuml
'https://plantuml.com/sequence-diagram
autonumber
title UC08 - Deactivate Device

autonumber

!pragma teoz true
box " <<System>>\n:SmartHome" #DarkGrey
box "<<Subsystem>>\n :Backend" #LightGrey
  participant ":Server" as server <<Container>>
end box

[o->server: Deactivate Device
activate server
server->server: find device
server->server: deactivate device
server->server: update device status


[o<--server: true
deactivate server
@enduml