@startuml
title US11: As Product Owner, I want the system to have a type of sensor that measures humidity (%).
'https://plantuml.com/class-diagram

interface Sensor {
+getSensorName()
+getSensorType()
+getUnit()
+getCurrentMeasurement()
}

class HumiditySensor {
-sensorName: String
-sensorType: SensorType
-unit: String
-currentMeasurement: int
+getSensorName()
+getSensorType()
+getUnit()
+getCurrentMeasurement()
}

enum SensorType {
HUMIDITY
TEMPERATURE
}

Sensor - HumiditySensor
HumiditySensor - SensorType

@enduml