@startuml
skinparam linetype polyline

node "localhost:" as client {

    component "Browser" as browser {
        component "UI" as UI {

        }
    }
}


node ":Server" as server  {
    component ":Smarthome\n<<System>>" as sh {
        component Frontend <<Subsystem>> {
        }

        component Backend <<Subsystem>> {
        }

        Backend -[bold]left- Database: http

        component Database <<Subsystem>> {
        }
    }

    port "Port 3000" as p3000
    port "Port 8080" as p8080

    Frontend -[bold]down- p3000
    Backend -[bold]down- p8080
}

UI --[bold]down-- p3000 :http
UI --[bold]down-- p8080 :http
@enduml