@startuml

skinparam linetype ortho

title Development View - Package Diagram - Level 3

package Backend {
    package controller {
    }

    package service {
    }

    package persistence {
    }

    package domain {
    }

    package mapper {
    }

    package utils {
    }
}

controller ..> service
controller ..> mapper

service ..> utils
service ..> persistence
service ..> domain

persistence ..> domain
persistence ..> utils

@enduml