@startuml

title US03 - As an Administrator, I want to have a list of existing rooms, so that I can choose one to edit it.

autonumber

participant ":ListAndEditRoomController" as ListAndEditRoomController
participant ":Room" as Room

-> ListAndEditRoomController: editRoom(roomDTOIdentifier, roomDTONewInfo)
activate ListAndEditRoomController

ListAndEditRoomController -> Room: editRoomConfiguration(newRoomName, newFloor, newRoomLength, newRoomWidth, newRoomHeight)
activate Room
alt room exists
    Room --> ListAndEditRoomController: true
else room does not exist
    Room --> ListAndEditRoomController: false
end
deactivate Room
 <-- ListAndEditRoomController: result
deactivate ListAndEditRoomController

@enduml