@startuml

title UC34.3 - Get the maximum instantaneous temperature difference between\n readings of the chosen sensor and a standard sensor outside.
autonumber

box "  <<System>>\n:SmartHome " #LightGrey
participant "<<Subsystem>>\n:Backend" as backend
end box

[o-> backend: get the maximum instantaneous temperature difference\n between readings of the chosen sensor and a standard sensor outside
activate backend
[o<-- backend: maximum instantaneous temperature
deactivate backend
@enduml