@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho

package server #LightGray {

title UC34: As a Room Owner [or Power User, or Administrator], I want to get the maximum instantaneous \n temperature difference between a device in the room and the outside, in a given period.

class HouseControllerWeb <RestController>{
     -houseService: HouseService
     -houseID: HouseID
     -roomService: RoomService
     -listDevicesByFunctionalityService: ListAllDevicesInHouseByFunctionalityService
     -roomMapperDTO: RoomMapperDTO
     -deviceMapperDTO: DeviceMapperDTO
     -actuatorFunctionalityMapperDTO: ActuatorFunctionalityMapperDTO
     -sensorFunctionalityMapperDTO: SensorFunctionalityMapperDTO
    +GET handleHouseQuery(@PathVariable String insideSensorIDString,\n@PathVariable String outsideSensorIDString, @RequestParam LocalDateTime givenStart,\n@RequestParam LocalDateTime givenEnd): ResponseEntity<>(maxTempDif, HttpStatus.OK)
    -maxTempDifOutsideInside(String insideSensorIDString, String outsideSensorIDString, \nLocalDateTime givenStar, LocalDateTime givenEnd)
}

class MaxTempDifOutsideInsideService <Service>{
    -valueRepository: InstantTimeValueRepository
    -configScraper: ConfigScraper
    -CONFIG_PROPERTIES = "config/config.properties": String
    +getMaxTemperatureDifference(SensorID insideSensorID, \n SensorID outsideSensorID, Timestamp startTime, \n Timestamp  endTime): double
    -findClosestTemperature(List<InstantTimeValue> values, \n long timestamp): double
}

class SensorID <VO> {
    -sensorName: String
}

interface InstantTimeValueRepository <repo> extends ValueRepository {
    +findBySensorId (SensorID sensorID): List<Value>
    +findAllEntities(): Iterable<Value>
}

interface Value{
    +getReading(): Reading
}

class InstantTimeValue implements Value {
    -valueID: ValueID
    -reading: Reading
    -sensorID: SensorID
    -instantTimeReading: Timestamp
    +getInstantTimeReading(): Timestamp
}

class Reading <VO> {
    -value: String
    -unit: String
    +getValue(): String
}


class ConfigScraper{
    -filePath: String
    -openingMainBlockTag: String
    -closingMainBlockTag: String
    -propertySplitter: String
    -functionalityProperty: String
    +loadTolerance(): String
}

HouseControllerWeb -- MaxTempDifOutsideInsideService
HouseControllerWeb --> SensorID: <<creates>>
MaxTempDifOutsideInsideService ..> Value: <<uses>>
MaxTempDifOutsideInsideService ..> InstantTimeValueRepository: <<uses>>
MaxTempDifOutsideInsideService -- ConfigScraper
InstantTimeValue - Reading

@enduml