@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho

title UC37.1: Get list of Devices with Actuator Functionality by Room

package server #LightGray {
class ActuatorFunctionalityControllerWeb {
    -actuatorFunctionalityService: ActuatorFunctionalityService
    -closeBlindRollerService: CloseBlindRollerService
   +GET getObjectByActuatorFunctionalityID(@PathVariable("id") String id, @RequestParam(value = "type", required = false) String type) : ResponseEntity<Object>(Collection.of(BlindRollerDTO), HttpStatus.OK)
   -getMapOfDeviceIDAndRoomIDAccordingToFunctionality(String id) : ResponseEntity<Object>(List<BlindRollerDTO>, HttpStatus.OK)
}

class ActuatorFunctionalityID <VO>{
    -actuatorFunctionalityID: String
}

class CloseBlindRollerService {
    - deviceRepository: DeviceRepository
    - actuatorRepository: ActuatorRepository
    +getMapOfDeviceIDAndRoomIDAccordingToFunctionality\n(ActuatorFunctionalityID actuatorFunctionalityID): Map<DeviceID, RoomID>
    -checkIfDeviceIsActive(DeviceID deviceID)
}

class DeviceID <VO>{
    -deviceID: String
}

class RoomID <VO>{
    -roomID: String
}

interface ActuatorRepository <repo>{
    +findByActuatorFunctionality(ActuatorFunctionalityID actuatorFunctionalityID): Iterable<Actuator>
}

class Actuator <root>{
     -actuatorID: ActuatorID
     -actuatorProperties: ActuatorProperties
     -deviceName: DeviceID
     -actuatorFunctionalityID: ActuatorFunctionalityID
     +getDeviceName(): DeviceID
    }

interface DeviceRepository <repo>{
    +findEntityByID(DeviceID deviceID): Optional<Device>
}

class Device <root>{
    -deviceID: DeviceID
    -deviceModel: DeviceModel
    -deviceStatus: DeviceStatus
    -roomID: RoomID
    +identity(): DeviceID
    +getRoomID(): RoomID
    +isActive(): boolean
}
}


ActuatorFunctionalityControllerWeb ..> ActuatorFunctionalityID: <<creates>>
ActuatorFunctionalityControllerWeb -- CloseBlindRollerService
CloseBlindRollerService -- ActuatorRepository
CloseBlindRollerService -- DeviceRepository
CloseBlindRollerService ..> RoomID: <<uses>>
CloseBlindRollerService ..> DeviceID: <<uses>>
ActuatorRepository -- Actuator
DeviceRepository -- Device
@enduml