
@startuml
title  PATCH Request
autonumber
skinparam sequenceMessageAlign center
skinparam actorBackgroundColor white
skinparam participantBackgroundColor white
skinparam sequenceReferenceBackgroundColor white
skinparam sequenceReferenceHeaderBackgroundColor white
skinparam sequenceGroupBackgroundColor white


box "<<Container>>\n:Server"
participant ":Controller" as controller <<Components>>
participant "dto:DTO" as dto
participant "vo:ValueObject" as vo
participant ":Service" as service <<Components>>
participant "domain:Domain" as domain <<Components>>
participant ":Repository" as repo <<Components>>

end box
autonumber
[o->controller : PATCH /Request
controller->vo** : create VOs from Request
controller->service : update(VOs)
service->repo : findById(id)
service <--repo : return Object
service->domain : update(Object)
domain-->service : updated Object
service ->repo : save updated Object
repo-->service : updated Object/boolean
service-->controller : updated Object/boolean
controller->dto** : convert Object to DTO
[o<--controller : updated ObjectDTO/boolean

legend bottom
 **This request can be included in:**
 |= Request PATCH |= Response |
 |= api/houses/{id} (UC01) |= HouseDTO  |
 |= api/rooms/{id} (UC03.2) |= RoomDTO|
 |= api/devices/{id} (UC08) |= boolean |
end legend

@enduml